### ISSUE TITLE
Issue on dev branch: AUTOMATIC MODERATION LOGGING FEATURES ARE BROKEN

### ISSUE THREAD

**Issue by TechGeekGamer** [Freshman-Devs/Apple-Explained-Moderation-Bot#7]
Everything that automatically logs stuff to the member's log (warning/mute/kick/ban/note) **is broken.** Please update **all automatic warn logging** to use the `userwarnings.json` file. (user.log and bot.log aren't affected by this.)

**Comment by ThatDerpiGuy** [comment]
Will do. We have not pulled to the bot yet, so do not worry.

**Comment by TechGeekGamer** [comment]
Ok, correction it _works_ but won't be visible.

**Comment by TechGeekGamer** [comment]
This needs to be fixed still, so don't see a reason for this to close.

**Comment by TechGeekGamer** [comment]
Corrected it to say all moderation logging features are broken.

**Comment by TechGeekGamer** [comment]
(except warn command)

**Comment by tommystefanatic** [comment]
I may not be on a PC right now, but there could be something wrong with the "fs" (filesystem) type commands. Try rechecking directories.
